
version: 2

models:
  - name: fb_daily_page_metrics
    description: "A starter dbt model"
    columns:
      - name: page_id
        description: "Facebook page id"
        
 

  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: post_id
        description: "Facebook post id"
