
version: 2

models:
  - name: fb_daily_page_metrics
    description: "A starter dbt model"
    columns:
      - name: page_id
        description: "Facebook page id"
        
 

  - name: fb_lifetime_post_analytics
    description: "A starter dbt model"
    columns:
      - name: post_id
        description: "Facebook post id"


  - name: insta_daily_page_metrics
    description: "A starter dbt model"
    columns:
      - name: post_id
        description: "Facebook post id"

  
  - name: insta_lifetime_page_metrics
    description: "A starter dbt model"
    columns:
      - name: post_id
        description: "Facebook post id"


  - name: insta_post_metrics
    description: "A starter dbt model"
    columns:
      - name: post_id
        description: "Facebook post id"
